export type StartWithConfiguration = (options: TrackConfiguration) => void
export type SetDataCollectionEnabled = (enabled: boolean) => void
export type SetLoginUserId = (userId: string, userKey ?: string) => void
export type CleanLoginUserId = () => void
export type SetLocation = (latitude: number, longitude: number) => void
export type TrackCustomEvent = (eventName: string, attributes ?: UTSJSONObject) => void
export type SetLoginUserAttributes = (attributes : UTSJSONObject) => void
export type GetDeviceId = () => string

export type TrackConfiguration = {
	accountId ?: string
	dataSourceId ?: string
	urlScheme ?: string
	debugEnabled ?: boolean
	cellularDataLimit ?: number
	dataUploadInterval ?: number
	sessionInterval ?: number
	dataValidityPeriod ?: number
	dataCollectionEnabled ?: boolean
	dataCollectionServerHost ?: string
	idMappingEnabled ?: boolean
	
	// android 特有配置
	channel ?: string
	androidIdEnabled ?: boolean
	imeiEnabled ?: boolean
	requireAppProcessesEnabled ?: boolean
}