import HashMap from 'java.util.HashMap'
import TrackConfiguration from 'com.growingio.android.sdk.track.TrackConfiguration'
import GrowingTracker from 'com.growingio.android.sdk.track.GrowingTracker'
import TrackMainThread from 'com.growingio.android.sdk.track.TrackMainThread'
import PageEvent from 'com.growingio.android.sdk.track.events.PageEvent'
import { UTSAndroid } from 'io.dcloud.uts'

import { TrackConfiguration as NativeTrackConfiguration,
	StartWithConfiguration,
	SetDataCollectionEnabled,
	SetLoginUserId,
	CleanLoginUserId,
	SetLocation,
	TrackCustomEvent,
	SetLoginUserAttributes,
	GetDeviceId,
	TrackPage
} from '../interface.uts'

export const startWithConfiguration: StartWithConfiguration = function (options: NativeTrackConfiguration) : void {
	if (options.accountId == null || options.urlScheme == null) {
		console.error("accountId or urlScheme is null")
		return
	}
	
	let trackConfiguration: TrackConfiguration = new TrackConfiguration(options.accountId, options.urlScheme)
	if (options.dataSourceId != null) {
		trackConfiguration.setDataSourceId(options.dataSourceId)
	}
	if (options.debugEnabled != null) {
		trackConfiguration.setDebugEnabled(options.debugEnabled!)
	}
	if (options.cellularDataLimit != null) {
		trackConfiguration.setCellularDataLimit(options.cellularDataLimit!.toInt())
	}
	if (options.dataUploadInterval != null) {
		trackConfiguration.setDataUploadInterval(options.dataUploadInterval!.toInt())
	}
	if (options.sessionInterval != null) {
		trackConfiguration.setSessionInterval(options.sessionInterval!.toInt())
	}
	if (options.dataValidityPeriod != null) {
		trackConfiguration.setDataValidityPeriod(options.dataValidityPeriod!.toInt())
	}
	if (options.dataCollectionEnabled != null) {
		trackConfiguration.setDataCollectionEnabled(options.dataCollectionEnabled!)
	}
	if (options.dataCollectionServerHost != null) {
		trackConfiguration.setDataCollectionServerHost(options.dataCollectionServerHost)
	}
	if (options.idMappingEnabled != null) {
		trackConfiguration.setIdMappingEnabled(options.idMappingEnabled!)
	}
	if (options.channel != null) {
		trackConfiguration.setChannel(options.channel)
	}
	if (options.androidIdEnabled != null) {
		trackConfiguration.setAndroidIdEnabled(options.androidIdEnabled!)
	}
	if (options.imeiEnabled != null) {
		trackConfiguration.setImeiEnabled(options.imeiEnabled!)
	}
	if (options.requireAppProcessesEnabled != null) {
		trackConfiguration.setRequireAppProcessesEnabled(options.requireAppProcessesEnabled!)
	}
	
	UTSAndroid.getDispatcher("main").async(function(_){
		GrowingTracker.startWithConfiguration(UTSAndroid.getAppContext(), trackConfiguration)
	},null)
}

export const setDataCollectionEnabled: SetDataCollectionEnabled = function(enabled: boolean) : void {
	UTSAndroid.getDispatcher("main").async(function(_){
		GrowingTracker.get().setDataCollectionEnabled(enabled)
	},null)
}

export const setLoginUserId: SetLoginUserId = function(userId: string, userKey ?: string) : void {
	UTSAndroid.getDispatcher("main").async(function(_){
		if (userKey == null) {
			GrowingTracker.get().setLoginUserId(userId)
		} else {
			GrowingTracker.get().setLoginUserId(userId, userKey)
		}
	},null)
}

export const cleanLoginuserId: CleanLoginUserId = function() : void {
	UTSAndroid.getDispatcher("main").async(function(_){
		GrowingTracker.get().cleanLoginUserId()
	},null)
}

export const setLocation: SetLocation = function(latitude: number, longitude: number) : void {
	UTSAndroid.getDispatcher("main").async(function(_){
		GrowingTracker.get().setLocation(latitude.toDouble(), longitude.toDouble())
	},null)
}

export const trackCustomEvent: TrackCustomEvent = function(eventName: string, attributes ?: UTSJSONObject) : void {
	UTSAndroid.getDispatcher("main").async(function(_){
		if (attributes == null) {
			GrowingTracker.get().trackCustomEvent(eventName)
		} else {
			let map = new HashMap<string, string>()
			attributes.toMap().forEach((value, key) => {
				if (typeof value == 'string') {
					map.put(key.toString(), value.toString())
				}
			})
			GrowingTracker.get().trackCustomEvent(eventName, map)
		}
	},null)
}

export const setLoginUserAttributes: SetLoginUserAttributes = function(attributes: UTSJSONObject) : void {
	UTSAndroid.getDispatcher("main").async(function(_){
		// 不能直接使用uts的map类型，uts的map类型是io.dcloud.uts.Map
		let map = new HashMap<string, string>()
		attributes.toMap().forEach((value, key) => {
			if (typeof value == 'string') {
				map.put(key.toString(), value.toString())
			}
		})
		GrowingTracker.get().setLoginUserAttributes(map)
	},null)
}

export const getDeviceId: GetDeviceId = function() : Promise<string> {
	return new Promise<string>((resolve, reject) => {
		UTSAndroid.getDispatcher("main").async(function(_){
			resolve(GrowingTracker.get().getDeviceId())
		},null)
		setTimeout(() => {
		    reject("get device_id failed");
		}, 1000)
	})
}

export const trackPage: TrackPage = function(pageName: string, attributes?: UTSJSONObject):void {
	UTSAndroid.getDispatcher("main").async(function(_){
		if (attributes == null) {
			TrackMainThread.trackMain().postEventToTrackMain(new PageEvent.Builder()
				.setPath(pageName))
		} else {
			let map = new HashMap<string, string>()
			attributes.toMap().forEach((value, key) => {
				if (typeof value == 'string') {
					map.put(key.toString(), value.toString())
				}
			})
			TrackMainThread.trackMain().postEventToTrackMain(new PageEvent.Builder()
				.setPath(pageName)
				.setAttributes(map))
		}
	},null)
}
