import { GrowingAnalytics, GrowingConfig, GrowingUniAppPlugin } from '@growingio/analytics'
import window from '@ohos.window'

import { TrackConfiguration as NativeTrackConfiguration,
	StartWithConfiguration,
	SetDataCollectionEnabled,
	SetLoginUserId,
	CleanLoginUserId,
	SetLocation,
	TrackCustomEvent,
	SetLoginUserAttributes,
	GetDeviceId,
	TrackPage
} from '../interface.uts'

let _window : window.Window

UTSHarmony.onAppAbilityWindowStageCreate((windowStage : window.WindowStage) => {
	_window = windowStage.getMainWindowSync()
})

export const startWithConfiguration: StartWithConfiguration = function (options: NativeTrackConfiguration) {
	if (options.accountId == null || options.urlScheme == null || options.dataSourceId == null) {
		console.error("accountId or dataSourceId or urlScheme is null")
		return
	}
	
	if (_window == null || _window == undefined) {
		console.error("call startWithConfiguration after ability windowStage create")
		return
	}
	
	let config: GrowingConfig = new GrowingConfig().NewSaaS(
		options.accountId,
		options.dataSourceId,
		options.urlScheme
	)
	if (options.debugEnabled != null) {
		config.debugEnabled = options.debugEnabled
	}
	if (options.dataUploadInterval != null) {
		config.dataUploadInterval = options.dataUploadInterval!
	}
	if (options.sessionInterval != null) {
		config.sessionInterval = options.sessionInterval!
	}
	if (options.dataValidityPeriod != null) {
		config.dataValidityPeriod = options.dataValidityPeriod!
	}
	if (options.dataCollectionEnabled != null) {
		config.dataCollectionEnabled = options.dataCollectionEnabled
	}
	if (options.dataCollectionServerHost != null) {
		config.dataCollectionServerHost = options.dataCollectionServerHost
	}
	if (options.idMappingEnabled != null) {
		config.idMappingEnabled = options.idMappingEnabled
	}
	
	let context = _window.getUIContext().getHostContext()
	GrowingAnalytics.start(context, config)
}

export const setDataCollectionEnabled: SetDataCollectionEnabled = function(enabled: boolean) : void {
	GrowingAnalytics.setDataCollectionEnabled(enabled)
}

export const setLoginUserId: SetLoginUserId = function(userId: string, userKey ?: string) : void {
	GrowingAnalytics.setLoginUserId(userId, userKey)
}

export const cleanLoginuserId: CleanLoginUserId = function() : void {
	GrowingAnalytics.cleanLoginUserId()
}

export const setLocation: SetLocation = function(latitude: number, longitude: number) : void {
	GrowingAnalytics.setLocation(latitude, longitude)
}

export const trackCustomEvent: TrackCustomEvent = function(eventName: string, attributes?: UTSJSONObject) : void {
	if (attributes == null) {
		GrowingAnalytics.track(eventName)
	} else {
		GrowingAnalytics.track(eventName, JSON.parse(JSON.stringify(attributes)))
	}
}

export const setLoginUserAttributes: SetLoginUserAttributes = function(attributes: UTSJSONObject) : void {
	GrowingAnalytics.setLoginUserAttributes(JSON.parse(JSON.stringify(attributes)))
}

export const getDeviceId: GetDeviceId = function() : Promise<string> {
	return Promise.resolve(GrowingAnalytics.getDeviceId())
}

export const trackPage: TrackPage = function(pageName: string, attributes?: UTSJSONObject):void {
	const argument = new Map<string, any>()
	
	argument.set('path', pageName)
	
	let attributesToMap = new Map<string, any>()
	for (const key in attributes) {
	  attributesToMap.set(key, attributes[key])
	}
	argument.set('attributes', attributesToMap)
	
	GrowingUniAppPlugin.trackUniAppPage(argument)
}